### ISSUE TITLE
SSL docs create an Issuer but tries to use it as a ClusterIssuer

### ISSUE THREAD

**Issue by diddledan** [openfaas/docs#116]
## Proposed change
Currently in the docs for SSL on kubernetes there is an example code block for a letsencrypt issuer that is specified as an `Issuer` type. These are confined within a specific namespace where a `ClusterIssuer` would be global. This is then contradicted by the certificate entry that tries to bind to a `ClusterIssuer` of the same name, which fails.

Specifically the types `Issuer` from the letsencrypt-issuer.yaml code block:

```yaml
# letsencrypt-issuer.yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: openfaas
spec:
  acme:
    # Email address used for ACME registration
    email: <your-email-here>
    http01: {}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      key: ""
      name: letsencrypt-prod
    server: https://acme-v01.api.letsencrypt.org/directory
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: openfaas
spec:
  acme:
    server: https://acme-staging.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: <your-email-here>
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
```

Conflicts with the use of `ClusterIssuer` in `openfaas-crt.yaml`:

```yaml
# openfaas-crt.yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: openfaas-crt
spec:
  secretName: openfaas-crt
  dnsNames:
    - openfaas.mydomain.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - openfaas.mydomain.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
```

## Context
The certificate generation failed because the `openfaas-crt` object references a non-existant `letsencrypt-prod`, or `letsencrypt-staging`, `ClusterIssuer` because we created those names as `Issuer`.

We need to choose to either set all these references as `Issuer` and ensure the objects are all in the same namespace or set the references to `ClusterIssuer`.

## Your Environment
* FaaS-CLI version ( Full output from: `faas-cli version` ): 0.8.3

* Docker version `docker version` (e.g. Docker 17.0.05 ): unsure - GKE version v1.11.5-gke.5

* Are you using Docker Swarm or Kubernetes (FaaS-netes)? Kubernetes on Google Cloud

* Operating System and version (e.g. Linux, Windows, MacOS): Linux
