### ISSUE TITLE
Label file reference code blocks with title

### ISSUE THREAD

**Issue by burtonr** [openfaas/docs#134]
## Proposed change

Update the code blocks that reference a file with formatting that adds a label to the code block for better clarity. Easier to see it's a file, and not a command/output

**example**
![Screenshot from 2019-03-08 21-24-11](https://user-images.githubusercontent.com/12687192/54073383-075d1800-424c-11e9-918d-ca2b1ba2b44f.png)

To accomplish this, we would add the following markdown to the file code blocks:
```
!!! example "secrets.yaml"
    ```yaml
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      creationTimestamp: null
      name: alexellis-fn-secrets
      namespace: openfaas-fn
    spec:
      encryptedData:
        incoming-webhook-url: (redacted)
    ```
```
> Note: The code block is also indented so that the outline will wrap the entire block

## Context
<!--- How has this issue affected you? What are you trying to accomplish? -->
<!--- Providing context helps us come up with a solution that is most useful in the real world -->
Want to make it easier to know that a block of code is reference to a file, and not some terminal input or output.


## Your Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* FaaS-CLI version ( Full output from: `faas-cli version` ):
0.8.3
* Docker version `docker version` (e.g. Docker 17.0.05 ):
18.06.3-ce
* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Both :smile: 

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 18.10

* Link to your project or a code example to reproduce issue:
Image included above
* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:
N/A
