### ISSUE TITLE
Typo Add TLS to openfaas

### ISSUE THREAD

**Issue by ivoreis** [openfaas/docs#150]
## Proposed change

The [Add TLS to openfaas](https://docs.openfaas.com/reference/ssl/kubernetes-with-cert-manager/#add-tls-to-openfaas) script contains a nested ingress entry. The correct script template should be:

```yaml
# tls.yml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: letsencrypt-staging
    certmanager.k8s.io/acme-challenge-type: http01
  tls:
    - hosts:
        - openfaas.mydomain.com
      secretName: openfaas-crt
  hosts:
    - host: openfaas.mydomain.com
      serviceName: gateway
      servicePort: 8080
      path: /
```

## Your Environment

* FaaS-CLI version ( Full output from: `faas-cli version` ):

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:
